export CUDA_VISIBLE_DEVICES=2
sh scripts/few-shot-horizon-6/weather-dlinear.sh
sh scripts/few-shot-horizon-6/etth1-dlinear.sh
sh scripts/few-shot-horizon-6/etth2-dlinear.sh
sh scripts/few-shot-horizon-6/ettm1-dlinear.sh
sh scripts/few-shot-horizon-6/ettm2-dlinear.sh
sh scripts/few-shot-horizon-6/electricity-dlinear.sh
sh scripts/few-shot-horizon-6/illness-dlinear.sh
sh scripts/few-shot-horizon-6/traffic-dlinear.sh